services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lumina-api-network

networks:
  lumina-api-network:
    driver: bridge

volumes:
  postgres_data: