# Generated by Django 5.2.17 on 2026-09-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareGiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('pause_time', models.TimeField()),
                ('cellphone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_insurance_plan_name', models.CharField(max_length=100)),
                ('membership_card_number', models.CharField(max_length=30)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('main_cellphone', models.CharField(max_length=15)),
                ('secondary_cellphone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.TimeField()),
                ('wakeup_time', models.TimeField()),
                ('bath_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('main_diagnosis', models.TextField(max_length=300)),
                ('religion', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=15)),
                ('genre', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')])),
                ('continuous_use_medicines', models.TextField()),
                ('blood_type', models.IntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, 'O+'), (8, 'O-')])),
                ('temperament', models.CharField(max_length=100)),
                ('hobbies', models.TextField(max_length=500)),
                ('secondary_health_problems', models.TextField(max_length=400)),
                ('hip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.healthinsuranceplan')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.responsible')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.routine')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.illness')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateField(auto_created=True)),
                ('date', models.DateField(auto_created=True)),
                ('room', models.CharField()),
                ('main_diagnosis', models.TextField(max_length=600)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('reaction', models.TextField(max_length=400)),
                ('trigger', models.TextField(max_length=300)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=10)),
                ('last_hour', models.TimeField(blank=True, null=True)),
                ('daily_frequency', models.CharField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_worker_gives_dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caregiver')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='api.patient')),
            ],
        ),
    ]
