from api.models.responsible import Responsible
from api.models.patient import Patient
from api.models.caregiver import CareGiver
from api.models.caregiver_patient import CaregiverPatient
from api.models.allergies import Allergies
from api.models.health_insurance_plan import HealthInsurancePlan
from api.models.hospitalization_data import HospitalizationData
from api.models.illness import Illness
from api.models.illness_patient import IllnessPatient
from api.models.medicine import Medicine
from api.models.patient_medicine import PatientMedicine
from api.models.routine import Routine